### ISSUE TITLE
apps folder

### ISSUE THREAD

**Issue by JulienNic0las** [pa-c/flaskApp#5]
D'un point organisation de l'app, je propose une modification de l'architecture. Je pense qu'un dossier *apps* situé à la racine et contenant toutes les applications python soit créé. Actuellement, si je ne dis pas de bêtises, les applications (`interpolate.py` et `test.py`) sont en vrac à la racine.

On aurait alors:
```
__init__.py
apps
  |__interpolation
       |__interpolate.py
  |__find_peaks
      |__peaks.py
static
templates
...
```

Qu'en dis-tu?

**Comment by pa-c** [comment]
exactement pour le moment c'est du gros vrac' . Tout à fait ok pour la réorganisation. J'ai créé un projet avec une todo list et In progress
